Gloriana
cetav-ddw/til pull request #22
Opened 2019-10-28 16:23 UTC by glorianaa80

2019-10-28 16:54 UTC, LuisArmando-TestCoder requested changes

2019-10-28 16:54 UTC, LuisArmando-TestCoder commented on src/posts/gloriana-2019-10-28.md
> +path: "/Image Replacement"
no mayúsculas en el path, tiene que estar separado por guiones

2019-10-28 16:54 UTC, LuisArmando-TestCoder commented on src/posts/gloriana-2019-10-28.md
> +
espacio de más

2019-10-29 01:36 UTC, jleiva requested changes

2019-10-29 01:36 UTC, jleiva commented on src/posts/gloriana-2019-10-28.md
> +Image Replacement te puede funcionar para cuando en tu sitio tiene que utilizar varias tipografías y no quieres cargarlas porque solo se utilizan una vez  en un título o en algo muy pequeño y si carg
podes darle una releida a este parrafo, porfa, le falta un par de comas por aqui y por alla

2019-10-29 20:52 UTC, merged