NPM package
cetav-ddw/til pull request #23
Opened 2019-10-29 22:47 UTC by hillaryCF

2019-10-29 23:44 UTC, glorianaa80 approved these changes
code review listo

2019-10-30 00:02 UTC, YethPenado commented on src/posts/Hillary-2019-10-29.md
> +date: "2019-10-28"
Hoy es 29

2019-10-30 00:02 UTC, YethPenado commented on src/posts/Hillary-2019-10-29.md
> +Tener pequeñas filas de código publicadas en NPM package nos facilitara un poco en nuestro flujo de trabajo,  ya que podemos acceder a ellas desde cualquier proyecto y con una sola línea de comando,
facilitará un poco nuestro flujo de trabajo*
Después de la coma en la palabra "trabajo", creo que hay un espacio de más.
Después de ese "dónde está", una coma después de "está". Además, en "no sabemos si tenemos" parece que hay espacios de más.

2019-10-30 00:02 UTC, YethPenado commented on src/posts/Hillary-2019-10-29.md
> +en la carpeta que creamos anteriormente, como último paso ejecutamos la siguiente línea de comando.
Ese "en la carpeta que creamos anteriormente" es mejor que vaya entre paréntesis, leerlo de corrido suena raro.

2019-10-30 00:02 UTC, YethPenado commented on src/posts/Hillary-2019-10-29.md
> +package.json. Este package.json
Queda mejor algo como "Este archivo contiene las dependencias básicas que se necesitan para publicar el proyecto".

2019-10-30 02:47 UTC, jleiva requested changes

2019-10-30 02:47 UTC, jleiva commented on src/posts/Hillary-2019-10-29.md
> +Tener pequeñas filas de código publicadas en NPM package nos facilitará un poco nuestro flujo de trabajo, ya que podemos acceder a ellas desde cualquier proyecto y con una sola línea de comando, lo c
porque filas?

una coma al final de _ya que_
> ...nuestro flujo de trabajo, ya que,

2019-10-30 16:45 UTC, merged