agrego post sobre optimización de imágenes
cetav-ddw/til pull request #29
Opened 2019-11-08 07:18 UTC by sauljlm

2019-11-08 15:16 UTC, jleiva requested changes

2019-11-08 15:16 UTC, jleiva commented on src/posts/saul-2019-11-8.md
> +path: "/Optimizar imágenes en webpack"
el path no lleva caracteres especiales, como tildes, las palabras se separan con guiones y no mayusculas

2019-11-08 15:16 UTC, jleiva commented on src/posts/saul-2019-11-8.md
> +Cuando desarrollamos apps, es importante que las imagenes esten obtimizadas para que el sitio tenga mejor performance, utilizando Webpack podemos obtimizar imagenes con el módulo image-webpack-loader
Una coma despues de para que `.., para que, cuando ...`

2019-11-08 17:21 UTC, YethPenado commented on src/posts/saul-2019-11-8.md
> +Cuando desarrollamos apps, es importante que las imagenes esten obtimizadas para que el sitio tenga mejor performance, utilizando Webpack podemos obtimizar imagenes con el módulo image-webpack-loader
imágenes*
optimizadas*
para que, cuando el sitio esté en producción, las imágenes pesen menos*

2019-11-08 17:24 UTC, YethPenado requested changes

2019-11-08 17:24 UTC, YethPenado commented on src/posts/saul-2019-11-8.md
> +  indicamos en qué calidad en porcentaje queremos las imágenes.
indicamos en qué calidad (en porcentaje) queremos las imágenes*

2019-11-20 22:06 UTC, LuisArmando-TestCoder commented on src/posts/saul-2019-11-11.md
> +Cuando desarrollamos apps, es importante que las imágenes esten optimizadas, para que, el sitio tenga mejor performance, utilizando Webpack podemos optimizar imagenes con el módulo image-webpack-load
estén

2019-11-20 22:07 UTC, LuisArmando-TestCoder requested changes

2019-11-20 22:07 UTC, LuisArmando-TestCoder commented on src/posts/saul-2019-11-11.md
> +Primero tenemos que tener las imagenes ubicadas en la carpeta src.
imágenes

2019-11-20 22:07 UTC, LuisArmando-TestCoder commented on src/posts/saul-2019-11-11.md
> +Cuando desarrollamos apps, es importante que las imágenes esten optimizadas, para que, el sitio tenga mejor performance, utilizando Webpack podemos optimizar imagenes con el módulo image-webpack-load
estén optimizadas

2019-11-20 23:33 UTC, merged