Mvptil
cetav-ddw/til pull request #3
Opened 2019-10-05 07:54 UTC by LuisArmando-TestCoder

2019-10-09 04:46 UTC, jleiva requested changes

2019-10-09 04:46 UTC, jleiva commented on src/helpers.scss
> +@mixin fontTitle {
esto deberian de ser variables, no mixins

2019-10-09 04:46 UTC, jleiva commented on src/components/article.scss
> +@import '../helpers';
todos los archivos de Sass deben seguir los estandares de CSS.

2019-10-09 04:46 UTC, jleiva commented on src/components/article.scss
> +  letter-spacing: 1px;
quedamos en remover el letter-spacing, no se ve bien, ni se lee bien

2019-10-09 04:46 UTC, jleiva commented on src/helpers.scss
> +$line: #DEDEDE;
en las variables deberiamos de tener valores que sean parte de la guia de estilos, no solo incluirlas por uso o repeticion

2019-10-09 04:46 UTC, jleiva commented on src/pages/index.scss
> +    background: $lineEnd;
lineEnd no tiene ninguna relacion con el background, mejor que el nombre de la variable sea el color

2019-10-09 04:46 UTC, jleiva commented on src/pages/index.scss
> +    background: #0000;
si usas shorthand para hexadecimales, la version corta solo tiene 3 valores, en este caso seria #000

2019-10-09 04:46 UTC, jleiva commented on src/pages/index.js
> +      <SEO title='Home' />
Inicio, o similar, el sitio esta en español

2019-10-09 04:46 UTC, jleiva commented on src/pages/index.js
> +            <hr className="article__title--line" />
porque hace falta poner hr, no se puede hacer lo mismo poniendole el border con CSS a alguno de los contenedores?

2019-10-11 19:56 UTC, LuisArmando-TestCoder commented on src/helpers.scss
> +@mixin fontTitle {
ready

2019-10-11 20:19 UTC, LuisArmando-TestCoder commented on src/components/article.scss
> +  letter-spacing: 1px;
ready

2019-10-12 18:18 UTC, merged

2019-10-17 16:46 UTC, jleiva commented
@all-contributors please add @LuisArmando-TestCoder  for code